#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");
const {
  DEFAULT_INPUT,
  DOCS_DIR,
  ensureOutputDirs,
  isValidHttpUrl,
  loadTaxonomy,
  mapCategory,
  parsePriceCents,
  parseRating,
  readRawProducts
} = require("./pipeline");

function audit(inputPath = DEFAULT_INPUT) {
  const rows = readRawProducts(inputPath);
  const taxonomyIndex = loadTaxonomy();
  const duplicateCounts = new Map();
  const categoryDistribution = new Map();
  const missingFields = new Map();
  const invalidPriceRows = [];
  const invalidRatingRows = [];
  const malformedUrlRows = [];
  const missingIngredientRows = [];
  const unknownCategoryRows = [];
  const fields = ["brand", "product", "product_type", "price", "rating", "details", "ingredients", "url", "store"];

  for (const row of rows) {
    const duplicateKey = JSON.stringify({
      brand: row.brand,
      product: row.product,
      product_type: row.product_type,
      price: row.price,
      rating: row.rating,
      details: row.details,
      ingredients: row.ingredients,
      url: row.url,
      store: row.store
    });
    duplicateCounts.set(duplicateKey, (duplicateCounts.get(duplicateKey) || 0) + 1);

    const category = row.product_type || "(blank)";
    categoryDistribution.set(category, (categoryDistribution.get(category) || 0) + 1);

    for (const field of fields) {
      if (!row[field] || String(row[field]).trim() === "") {
        missingFields.set(field, (missingFields.get(field) || 0) + 1);
      }
    }

    if (!row.ingredients || row.ingredients.trim() === "") missingIngredientRows.push(row.source_row_id);
    if (parsePriceCents(row.price) == null) invalidPriceRows.push(row.source_row_id);
    if (parseRating(row.rating) == null) invalidRatingRows.push(row.source_row_id);
    if (!isValidHttpUrl(row.url)) malformedUrlRows.push(row.source_row_id);
    if (mapCategory(row.product_type, taxonomyIndex).slug === "unknown") unknownCategoryRows.push(row.source_row_id);
  }

  const duplicateRows = [...duplicateCounts.values()].reduce((total, count) => total + Math.max(0, count - 1), 0);
  return {
    source_file: path.relative(process.cwd(), inputPath),
    generated_at: new Date().toISOString(),
    total_rows: rows.length,
    duplicate_rows: duplicateRows,
    category_distribution: Object.fromEntries([...categoryDistribution.entries()].sort((a, b) => b[1] - a[1])),
    missing_fields: Object.fromEntries([...missingFields.entries()].sort()),
    missing_ingredient_rows: missingIngredientRows,
    invalid_price_rows: invalidPriceRows,
    invalid_rating_rows: invalidRatingRows,
    malformed_url_rows: malformedUrlRows,
    unknown_category_rows: unknownCategoryRows
  };
}

function formatRowList(rows) {
  if (rows.length === 0) return "None";
  const preview = rows.slice(0, 25).join(", ");
  return rows.length > 25 ? `${preview}, ... (${rows.length} total)` : preview;
}

function toMarkdown(report) {
  const categoryRows = Object.entries(report.category_distribution)
    .map(([category, count]) => `| ${category} | ${count} |`)
    .join("\n");
  const missingRows = Object.entries(report.missing_fields)
    .map(([field, count]) => `| ${field} | ${count} |`)
    .join("\n");

  return `# Data Audit Report

Generated: ${report.generated_at}

Source: \`${report.source_file}\`

## Summary

| Metric | Value |
| --- | ---: |
| Total rows | ${report.total_rows} |
| Duplicate rows | ${report.duplicate_rows} |
| Missing ingredient lists | ${report.missing_ingredient_rows.length} |
| Invalid prices | ${report.invalid_price_rows.length} |
| Invalid ratings | ${report.invalid_rating_rows.length} |
| Malformed URLs | ${report.malformed_url_rows.length} |
| Unknown categories | ${report.unknown_category_rows.length} |

## Category Distribution

| Category | Rows |
| --- | ---: |
${categoryRows}

## Missing Fields

| Field | Missing rows |
| --- | ---: |
${missingRows || "| None | 0 |"}

## Row Samples For Cleanup

| Check | Source row IDs |
| --- | --- |
| Missing ingredients | ${formatRowList(report.missing_ingredient_rows)} |
| Invalid prices | ${formatRowList(report.invalid_price_rows)} |
| Invalid ratings | ${formatRowList(report.invalid_rating_rows)} |
| Malformed URLs | ${formatRowList(report.malformed_url_rows)} |
| Unknown categories | ${formatRowList(report.unknown_category_rows)} |

## Notes

- Source row IDs come from the scraped \`index\` column when available.
- This report is generated by \`node scripts/audit_data.js\`.
- Ingredient completeness is informational only; it is not a medical or safety guarantee.
`;
}

function main() {
  const inputPath = process.argv[2] ? path.resolve(process.argv[2]) : DEFAULT_INPUT;
  ensureOutputDirs();
  const report = audit(inputPath);
  const outputPath = path.join(DOCS_DIR, "data_audit_report.md");
  fs.writeFileSync(outputPath, toMarkdown(report), "utf8");
  console.log(`Audited ${report.total_rows} rows from ${path.relative(process.cwd(), inputPath)}`);
  console.log(`Wrote ${path.relative(process.cwd(), outputPath)}`);
}

if (require.main === module) {
  main();
}

module.exports = { audit, toMarkdown };
